const products = [
  {
    productId: crypto.randomUUID(),
    productName: "iPhone 18 Duo",
    price: 299999,
    category: "Electronics",
    rating: 4.8,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Samsung Galaxy S26 Ultra",
    price: 145999,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Sony WH-1000XM6 Headphones",
    price: 34999,
    category: "Electronics",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Dell XPS 15 Laptop",
    price: 189999,
    category: "Electronics",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Levi's 511 Slim Fit Jeans",
    price: 4999,
    category: "Clothing",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Dri-FIT Training T-Shirt",
    price: 2499,
    category: "Clothing",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Zara Oversized Wool Coat",
    price: 8999,
    category: "Clothing",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Air Max 270",
    price: 12999,
    category: "Shoes",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Ultraboost 24",
    price: 15999,
    category: "Shoes",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Puma RS-X Running Shoes",
    price: 8999,
    category: "Shoes",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Atomic Habits by James Clear",
    price: 899,
    category: "Books",
    rating: 4.9,
  },
  {
    productId: crypto.randomUUID(),
    productName: "The Psychology of Money",
    price: 699,
    category: "Books",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Clean Code by Robert C. Martin",
    price: 1499,
    category: "Books",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Ray-Ban Aviator Sunglasses",
    price: 8999,
    category: "Accessories",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Fossil Gen 6 Smartwatch",
    price: 19999,
    category: "Accessories",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Leather Wallet - Brown",
    price: 1999,
    category: "Accessories",
    rating: 4.1,
  },

  // ---------- Apple ----------
  {
    productId: crypto.randomUUID(),
    productName: "iPhone 13",
    price: 59999,
    category: "Electronics",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "iPhone 14",
    price: 69999,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "iPhone 15",
    price: 79999,
    category: "Electronics",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "MacBook Air M2",
    price: 114999,
    category: "Electronics",
    rating: 4.8,
  },
  {
    productId: crypto.randomUUID(),
    productName: "iPad Air 5",
    price: 59999,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "AirPods Pro 2",
    price: 24999,
    category: "Electronics",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Apple Watch Series 9",
    price: 41999,
    category: "Accessories",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Apple Leather Case",
    price: 4999,
    category: "Accessories",
    rating: 4.2,
  },

  // ---------- Samsung ----------
  {
    productId: crypto.randomUUID(),
    productName: "Samsung Galaxy S23",
    price: 74999,
    category: "Electronics",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Samsung Galaxy S24",
    price: 84999,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Samsung Galaxy Buds 2",
    price: 12999,
    category: "Electronics",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: 'Samsung Smart TV 55"',
    price: 65999,
    category: "Electronics",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Samsung Galaxy Watch 6",
    price: 29999,
    category: "Accessories",
    rating: 4.4,
  },

  // ---------- Nike ----------
  {
    productId: crypto.randomUUID(),
    productName: "Nike Air Max 270",
    price: 12999,
    category: "Shoes",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Revolution 7",
    price: 4999,
    category: "Shoes",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Dri-FIT T-Shirt",
    price: 2499,
    category: "Clothing",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Sportswear Hoodie",
    price: 4499,
    category: "Clothing",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Brasilia Backpack",
    price: 3499,
    category: "Accessories",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Duffle Bag",
    price: 3999,
    category: "Accessories",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Nike Cap",
    price: 1499,
    category: "Accessories",
    rating: 4.1,
  },

  // ---------- Adidas ----------
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Ultraboost 24",
    price: 15999,
    category: "Shoes",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Superstar",
    price: 7999,
    category: "Shoes",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Tiro Track Pants",
    price: 3499,
    category: "Clothing",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Essentials Tee",
    price: 1999,
    category: "Clothing",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Adidas Classic Backpack",
    price: 2999,
    category: "Accessories",
    rating: 4.3,
  },

  // ---------- Puma ----------
  {
    productId: crypto.randomUUID(),
    productName: "Puma RS-X",
    price: 8999,
    category: "Shoes",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Puma Smash v2",
    price: 3999,
    category: "Shoes",
    rating: 4.1,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Puma Training Shorts",
    price: 1799,
    category: "Clothing",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Puma Phase Backpack",
    price: 2499,
    category: "Accessories",
    rating: 4.0,
  },

  // ---------- Levi's ----------
  {
    productId: crypto.randomUUID(),
    productName: "Levi's 511 Slim Jeans",
    price: 4999,
    category: "Clothing",
    rating: 4.3,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Levi's 501 Original",
    price: 5499,
    category: "Clothing",
    rating: 4.5,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Levi's Trucker Jacket",
    price: 6999,
    category: "Clothing",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Levi's Leather Belt",
    price: 1999,
    category: "Accessories",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Levi's Wallet",
    price: 1499,
    category: "Accessories",
    rating: 4.1,
  },

  // ---------- Sony ----------
  {
    productId: crypto.randomUUID(),
    productName: "Sony WH-1000XM5",
    price: 29999,
    category: "Electronics",
    rating: 4.7,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Sony WF-1000XM5 Earbuds",
    price: 19999,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Sony PlayStation 5",
    price: 54999,
    category: "Electronics",
    rating: 4.8,
  },
  {
    productId: crypto.randomUUID(),
    productName: 'Sony Bravia 43" TV',
    price: 45999,
    category: "Electronics",
    rating: 4.4,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Sony DualSense Controller",
    price: 5999,
    category: "Accessories",
    rating: 4.5,
  },

  // ---------- Boat ----------
  {
    productId: crypto.randomUUID(),
    productName: "Boat Rockerz 450",
    price: 1499,
    category: "Electronics",
    rating: 4.1,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Boat Airdopes 141",
    price: 1299,
    category: "Electronics",
    rating: 4.0,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Boat Stone 350 Speaker",
    price: 1999,
    category: "Electronics",
    rating: 4.2,
  },
  {
    productId: crypto.randomUUID(),
    productName: "Boat Smartwatch Storm",
    price: 2499,
    category: "Accessories",
    rating: 4.0,
  },
];
export default products;
